import os, shutil, ntpath, glob, sys

# move to source directory
os.chdir(os.path.dirname(os.path.abspath(__file__)))

# copy C++ Binding Generator scripts
targetPath = '../Core/scripts/bindings'
outputPath = "./Bindings"

if os.path.exists(outputPath):
    print('Directory {} exists'.format(outputPath))
    shutil.rmtree(outputPath)
    print('Removed directory {}'.format(outputPath))

shutil.copytree(targetPath, outputPath)
print('Copied directory {} to {}'.format(targetPath, outputPath))


from Bindings import define
from Bindings import auto_generate_define
from Bindings.CppBindingGenerator import BindingGeneratorCSharp

# generate C# binding
args = sys.argv
lang = 'ja'
if len(args) >= 3 and args[1] == '-lang':
    if args[2] in ['ja', 'en']:
        lang = args[2]
    else:
        print('python csharp.py -lang [ja|en]')

define.load_text_from_json_file('Bindings/desc.json')
define.load_text_from_json_file('Bindings/desc_profiler.json')
define.load_text_from_json_file('Bindings/desc_media.json')

bindingGenerator = BindingGeneratorCSharp(define, [], lang)
bindingGenerator.output_path = '../Engine/AutoGeneratedCoreBindings.cs'
bindingGenerator.dll_name = 'Altseed2_Core'
bindingGenerator.namespace = 'Altseed2'
bindingGenerator.generate()
